name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - bqplot
  - matplotlib
  - numpy
  - jupyterlab_widgets
  - ipywidgets
  - micropip
  - scikit-learn=1.1
