name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - bqplot
  - matplotlib
  - numpy=1.23.0
  - scipy=1.3.2
  - jupyterlab_widgets
  - ipywidgets
  - micropip
  - scikit-learn=1.1
